### ISSUE TITLE
factorization fails for rook pivoting with zero columns

### ISSUE THREAD

**Issue by joaoleal** [nwh/lusol#6]
Factorization using rook pivoting provides a bad U matrix when there are columns with zeros.
Here is a simple example:
```matlab
A = sparse([1,0,0,0,0;...
            0,0,0,1,0;...
            0,0,0,0,1]);
            
options = lusol_obj.luset('pivot', 'TRP');
mylu = lusol_obj(A, options);
[U, P, Q] = mylu.U('matrix');
[L0] = mylu.L0('matrix');

fprintf('U matrix: \n'); disp(full(U));
fprintf('L0 matrix: \n'); disp(full(L0));
```
In my system (Ubuntu 14.04, 64bit, gfortran 4.8.2) I get the following output:

    U matrix: 
         1     0     0     0     0
         0     0     0     0     0
         0     0     1     0     0

    L0 matrix: 
         1     0     0
         0     1     0
         0     0     1

the second row of U is not OK.

Changing pivoting to partial pivoting will produce the correct results.
Also all tests in lusol_test.m pass. 

No changes were performed to the source code. 
The only change was the path to matlab in the makefile.

**Comment by nwh** [comment]
This is known to Michael Saunders as a bug in the LUSOL fortran code.

**Comment by nwh** [comment]
Output using <https://github.com/nwh/lusol/releases/tag/build-2016-01-26>:

```
U matrix: 
     1     0     0     0     0
     0     1     0     0     0
     0     0     1     0     0

L0 matrix: 
     1     0     0
     0     1     0
     0     0     1
```

Works now!
